### ISSUE TITLE
replace xPRO logo with mitxonline logo 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline-theme#1]
replace this /lms/static/images/logo.png with the logo [from invision](https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/455419669/preview?scrollOffset=234) (header top left)

**Comment by pdpinch** [comment]
LOGO_TRADEMARK_URL should maybe be set to the open edX logo, https://edx-cdn.org/v3/default/logo-trademark.svg

**Comment by asadiqbal08** [comment]
Get the top left from design. 

<img width="343" alt="Screen Shot 2021-08-12 at 4 51 33 PM" src="https://user-images.githubusercontent.com/7334669/129192061-95c17fb6-873b-405f-8a14-beb2207c9ed4.png">

**Comment by pdpinch** [comment]
The goal is to make it look the same as xPRO, but with an MITx Online logo. 

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/430126/129194775-cb91dd89-0a6b-4721-9f97-4e277ea6c08b.png">

I don't know why the image would be centered as in your first screenshot, but the logo should appear to the left of the menu.

**Comment by pdpinch** [comment]
This doesn't seem to be working on the [QA server](lms-qa.mitxonline.mit.edu)

<img width="1566" alt="image" src="https://user-images.githubusercontent.com/430126/129937175-fe5d1d25-5922-4eb7-85e6-61dd5add4349.png">

Do we need to set an environment variable somewhere?

**Comment by asadiqbal08** [comment]
@pdpinch are we sure the theme is applied to QA instance ?

**Comment by asadiqbal08** [comment]
@pdpinch , I guess, We need to create a separate story to investigate the **image not loading issue** in header && footer sections of https://courses-qa.mitxonline.mit.edu/
I am saying this because, images are loading fine over my local Devstack as shown in the images of [Footer-PR](https://github.com/mitodl/mitxonline-theme/pull/19)

**Comment by asadiqbal08** [comment]
We can now close this story, see the below image. 


<img width="1416" alt="Screen Shot 2021-08-25 at 8 40 20 AM" src="https://user-images.githubusercontent.com/7334669/130722623-8d11f30d-2788-4520-b2f2-800add71117f.png">

**Comment by asadiqbal08** [comment]
@pdpinch can we close this ?
