### ISSUE TITLE
Need to update the contact_us page

### ISSUE THREAD

**Issue by asadiqbal08** [mitodl/mitxonline-theme#11]
Currently, 

> Contact Us
> Find answers to common questions asked by xPRO learners in the MIT xPRO Help Center.
> 
> For other support questions, please submit your question here.

**Comment by pdpinch** [comment]
For now, replace with:

> Find answers to common questions asked by Micromasters learners in the MITx MicroMasters Help Center.

with links to:

https://mitx-micromasters.zendesk.com/hc
and
https://mitx-micromasters.zendesk.com/hc/requests/new
