### ISSUE TITLE
Update edx ACE email template

### ISSUE THREAD

**Issue by asadiqbal08** [mitodl/mitxonline-theme#12]
This email template is used when generating enrollment emails, and probably other transactional emails. 

https://github.com/mitodl/mitxonline-theme/blob/main/lms/templates/ace_common/edx_ace/common/base_body.html#L65

### acceptance criteria:

- [x] MITx Online logo
- [x] Link logo to MITx Online dashboard (on RC, this is https://rc.mitxonline.mit.edu/dashboard) 
- [x] Sign in link should go to MITx Online sign in page (on RC, this is https://rc.mitxonline.mit.edu/signin)
- [ ] "Access the Course Materials Now" button should work
- [x] Mailing address should be populated and not display "SET-ME-PLEASE" (this is probably an environment setting) 
- [x] Copyright string should use platform name, or be hardcoded to "MITx Online" 
- [ ] Return address should be set to "MITx Online" <mitxonline-support@mit.edu> (I'm pretty sure this is an environment setting; see https://github.com/mitodl/ol-infrastructure/issues/327) 

<img width="798" alt="image" src="https://user-images.githubusercontent.com/430126/129959959-611d87f3-d3d7-4c9e-ad6e-b569bd4c569a.png">

**Comment by pdpinch** [comment]
do you have a link or links?

**Comment by asadiqbal08** [comment]
I came over this URL under this file. 
https://github.com/mitodl/mitxonline-theme/blob/main/lms/templates/ace_common/edx_ace/common/base_body.html#L65

**Comment by asadiqbal08** [comment]
also thie  section under the same file have `xPro` text.

**Comment by pdpinch** [comment]
I updated the description with some more specific details.

**Comment by pdpinch** [comment]
Looks like some of these are already fixed on lms-qa. I need to do some more testing.

**Comment by pdpinch** [comment]
@briangrossman can you review the checklist to see if there's anything further that needs to be done here?

**Comment by briangrossman** [comment]
@pdpinch & @asadiqbal08 

Ran a test. Looks like all these still need to be addressed:

![image](https://user-images.githubusercontent.com/21342568/134053011-1812eaf7-88db-4e8f-a760-134bc3c70496.png)


- [ ] **MITx Online logo** 
   - *Still pointing to xPRO*
- [ ] **Link logo to MITx Online dashboard (on RC, this is https://rc.mitxonline.mit.edu/dashboard)** 
   - *Sent me to:*
   - https://m4vdsnxv.r.us-east-1.awstrack.me/L0/https:%2F%2Flms-qa.mitxonline.mit.edu%2F%3Futm_source=instructor%26utm_medium=email%26utm_campaign=allowedenroll%26utm_content=b7a605b9-845e-4797-800c-0bf702db2e55/1/0100017c04680a89-47572213-848b-4bbb-aebc-f22d699cdb7c-000000/OjbHv36qpr8XBw8f71yE811sVIY=236 
   - which redirects me to 
   - https://lms-qa.mitxonline.mit.edu/?utm_source=instructor&utm_medium=email&utm_campaign=allowedenroll&utm_content=b7a605b9-845e-4797-800c-0bf702db2e55 
   - which loads as a blank page with the error `This site can’t be reachedCheck if there is a typo in lms-qa.mitxonline.mit.edu.`
- [ ] **Sign in link should go to MITx Online sign in page (on RC, this is https://rc.mitxonline.mit.edu/signin)**
   - *Sent me to:*
   - https://m4vdsnxv.r.us-east-1.awstrack.me/L0/https:%2F%2Flms-qa.mitxonline.mit.edu%2F%3Futm_source=instructor%26utm_medium=email%26utm_campaign=allowedenroll%26utm_content=b7a605b9-845e-4797-800c-0bf702db2e55/2/0100017c04680a89-47572213-848b-4bbb-aebc-f22d699cdb7c-000000/4xV8ET6cw4b3lIQWQASdCeynmBo=236
   - which redirects me to: 
   - https://lms-qa.mitxonline.mit.edu/?utm_source=instructor&utm_medium=email&utm_campaign=allowedenroll&utm_content=b7a605b9-845e-4797-800c-0bf702db2e55
   - which loads as a blank page with the error `This site can’t be reachedCheck if there is a typo in lms-qa.mitxonline.mit.edu.`
- [ ] **"Access the Course Materials Now" button should work** 
   - *Sorry... I don't see this button. Do you mean the `Finish Your Registration` button? 'cause that doesn't link anywhere.* 
- [x] **Mailing address should be populated and not display "SET-ME-PLEASE" (this is probably an environment setting)** 
- [ ] **Copyright string should use platform name, or be hardcoded to "MITx Online"** 
   - *Still says MIT xPRO*
- [ ] **Return address should be set to "MITx Online" <mitxonline-support@mit.edu> (I'm pretty sure this is an environment setting; see https://github.com/mitodl/ol-infrastructure/issues/327)** 
   - *Return address is: `support@edxapp-mail-qa.mitxonline.mit.edu`*

**Comment by asadiqbal08** [comment]
@pdpinch this ticket is not in the Arbisoft board, should it be ready to work ?

**Comment by asadiqbal08** [comment]
@pdpinch can you please looked over this @briangrossman comment

> "Access the Course Materials Now" button should work
> Sorry... I don't see this button. Do you mean the Finish Your Registration button? 'cause that doesn't link anywhere.

**Comment by asadiqbal08** [comment]
Ok @briangrossman , What I get, if you have a pending registration then it show the `Finish Your Registration` button otherwise it shows up the `Access the Course Materials Now ` button.

**Comment by briangrossman** [comment]
@asadiqbal08 

I see. Thanks. I guess we should make sure both cases work. Note that the `Finish Your Registration` button wasn't linked at all.

**Comment by asadiqbal08** [comment]
@pdpinch Referring to this:

>  Link logo to MITx Online dashboard (on RC, this is https://rc.mitxonline.mit.edu/dashboard)
> Sign in link should go to MITx Online sign in page (on RC, this is https://rc.mitxonline.mit.edu/signin)


I was trying to update the `Sign In` and `Dashboard` URL from the site configuration but the requested changes were not rendering over the email UI and after looking around, I came to know that one of the template context for ACE emails is not being called while sending bulk enrollment emails from instructor dashboard in edx-platform (I am on `OPENEDX_RELEASE/lilac.master`), [Referring this block](https://github.com/edx/edx-platform/blob/master/openedx/core/djangoapps/ace_common/template_context.py#L13-L47)

There are two possible solutions. 
1- Create an upstream PR to call this ace template context for getting extra details in case of enrollments too.
**OR**
2- Used the `site_configuration_values` in our mitxonline-theme repository as I did in my [PR HERE](https://github.com/mitodl/mitxonline-theme/pull/25/files#diff-8837e91672139956ef9117136e4c27f5167cd666374543107691b8d33e3ef935)

Let me know do you think and I have these site configurations over my local instance. 

```
{
  "ENABLE_MKTG_SITE": true,
  "COURSE_CATALOG_API_URL": "http://edx.devstack.discovery:18381/api/v1/",
  "PLATFORM_NAME": "Mitx Online",
  "FOOTER_ORGANIZATION_IMAGE": "images/logo.png",
  "SIGNIN_URL": "/signin",
  "HOMEPAGE_URL": "/dashboard",
  "MKTG_URLS": {
    "ABOUT": "/about-us",
    "CONTACT": "http://mitx-micromasters.zendesk.com/hc/en-us/requests/new",
    "TOS": "/terms-of-service",
    "HONOR": "/honor"
  }
}

```

**Comment by pdpinch** [comment]
>There are two possible solutions.
>1- Create an upstream PR to call this ace template context for getting extra details in case of enrollments too.
>OR
>2- Used the site_configuration_values in our mitxonline-theme repository as I did in my PR HERE

Let's go with option 2, since it should be faster and we'd like to fix this before Oct. 1. 

>Secondly,
> "Access the Course Materials Now" button should work

It does seem like a misconfiguration somewhere. In the QA stack, the button should like to courses-qa.mitxonline.mit.edu and not lms-qa.mitxonline.mit.edu -- can you determine where that value is being set?

**Comment by asadiqbal08** [comment]
> It does seem like a misconfiguration somewhere. In the QA stack, the button should like to courses-qa.mitxonline.mit.edu and not lms-qa.mitxonline.mit.edu -- can you determine where that value is being set?

It seems to me, site configuration is not properly set. 

<img width="1131" alt="Screen Shot 2021-09-28 at 11 53 35 AM" src="https://user-images.githubusercontent.com/7334669/135037737-010651c6-9494-418d-b5b3-8c477095eccd.png">

**Comment by asadiqbal08** [comment]
@pdpinch are you pointing to `From` address in this point ? 

> Return address should be set to "MITx Online" mitxonline-support@mit.edu

**Comment by pdpinch** [comment]
> It seems to me, site configuration is not properly set. 

<img width="1131" alt="Screen Shot 2021-09-28 at 11 53 35 AM" src="https://user-images.githubusercontent.com/7334669/135037737-010651c6-9494-418d-b5b3-8c477095eccd.png">

How do we change this? It looks like a django admin snapshot. What's the URL? (fyi @briangrossman )

**Comment by pdpinch** [comment]
> @pdpinch are you pointing to From address in this point ?
> >  Return address should be set to "MITx Online" mitxonline-support@mit.edu

Yes, I'm referring to the From address.

**Comment by asadiqbal08** [comment]
> > It seems to me, site configuration is not properly set.
> 
> <img alt="Screen Shot 2021-09-28 at 11 53 35 AM" width="1131" src="https://user-images.githubusercontent.com/7334669/135037737-010651c6-9494-418d-b5b3-8c477095eccd.png">
> 
> How do we change this? It looks like a django admin snapshot. What's the URL? (fyi @briangrossman )

Yes it is site admin and the screenshot is referring this [site_configuration](https://courses-qa.mitxonline.mit.edu/admin/site_configuration/siteconfiguration/1/change/)
