### ISSUE TITLE
footer issues 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline-theme#17]
The mitxonline should resemble the xPRO footer:

<img width="304" alt="image" src="https://user-images.githubusercontent.com/430126/129938496-d3fd593b-39b9-45ba-9ed9-ba56dac36edc.png">

### acceptance criteria:

- [ ] "About" should link to the Marketing site / about-us (on RC, that would be https://rc.mitxonline.mit.edu/about-us/) 
- [ ] "Support Center" should link to https://mitx-micromasters.zendesk.com/hc (until we have an MITx Online help center) 
- [ ] "Contact Us" should link to https://mitx-micromasters.zendesk.com/hc/en-us/requests/new (until we have an MITx Online help center) 
- [ ] Terms of Service and Honor code should be separate links. Terms of service links to [`/terms-of-service` on the marketing site](https://rc.mitxonline.mit.edu/terms-of-service). Honor code links to [`/honor-code` on the marketing site](https://rc.mitxonline.mit.edu/honor-code/)
- [ ] On courses-qa.mitxonline.mit.edu, the logo isn't loading.

<img width="1727" alt="Screen Shot 2021-08-18 at 12 41 12 PM" src="https://user-images.githubusercontent.com/430126/129938166-32f8da0a-0b0e-4bcb-af18-737ad0018463.png">

Do we need to set an environment variable?

**Comment by suru77** [comment]
hi 

I can link  = about , support center, and contact us pages

**Comment by asadiqbal08** [comment]
@pdpinch regarding the footer image, I found, edx branding api is trying to make an absolute URL [here](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/branding/api.py#L470), I am not sure but I guess, Django template is expecting a relative path). What I did for testing, I set the `FOOTER_ORGANIZATION_IMAGE: '' ` in site configurations and getting the expected image in footer section. 

<img width="794" alt="Screen Shot 2021-08-23 at 5 47 00 PM" src="https://user-images.githubusercontent.com/7334669/130449571-dea0d7f9-2249-4897-b6e2-ee96e4866def.png">

Kindly see [this-1](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/branding/api.py#L460-L468) and [this-2](https://github.com/edx/edx-platform/blob/master/lms/templates/footer.html#L31-L38) comments.

**Comment by asadiqbal08** [comment]
Kindly see the [PR](https://github.com/mitodl/mitxonline-theme/pull/19#issue-978025722)

**Comment by asadiqbal08** [comment]
Regarding the image issue over footer & header section of QA instance. See [comment](https://github.com/mitodl/mitxonline-theme/issues/1#issuecomment-904592554)
