### ISSUE TITLE
Remove signup button from studio home page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline-theme#26]
We don't want users creating accounts by visiting studio and then accessing the register page. 

in xpro, we remove the "Sign Up" link from the index page on cms. We should do the same thing here. 

Compare: https://studio-rc.xpro.mit.edu/ to https://studio-qa.mitxonline.mit.edu/

**Comment by umarmughal824** [comment]
@pdpinch we need to set the `ALLOW_PUBLIC_ACCOUNT_CREATION` flag to `False` in edx-platform to hide the button.

Also, there is one upstream PR that is associated with it

https://github.com/edx/edx-platform/pull/29261

**Comment by pdpinch** [comment]
If we do that, it prevents us from using OAUTH to create new accounts. We have to hide the link instead.

**Comment by umarmughal824** [comment]
> When we tried that in the past, it prevented OAuth from creating new accounts. In xPRO we ended up just hiding the button in the template.

@pdpinch it was a bug in edx-platform that has been addressed in edx/edx-platform#29261. As this PR got merged so from now on by setting that flag it will also hide the button.

**Comment by pdpinch** [comment]
Thanks for the pointer, but as far as I can tell, that PR only addresses the front-end issue. The problem we have with setting this flag `ALLOW_PUBLIC_ACCOUNT_CREATION` is that users can't create accounts with OAuth, which we need for mitxonline to function. 

See https://github.com/mitodl/ol-infrastructure/blob/47f8aac8d5ae046982a63647e77837594e537c2e/src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml#L252

If there's reason to think that the behavior of `ALLOW_PUBLIC_ACCOUNT_CREATION` has changed, I would be willing to try setting the flag. But we would need to be sure that account creation from the mitxonline application still works.

**Comment by umarmughal824** [comment]
> Thanks for the pointer, but as far as I can tell, that PR only addresses the front-end issue. The problem we have with setting this flag `ALLOW_PUBLIC_ACCOUNT_CREATION` is that users can't create accounts with OAuth, which we need for mitxonline to function.
> 
> See https://github.com/mitodl/ol-infrastructure/blob/47f8aac8d5ae046982a63647e77837594e537c2e/src/bilder/images/edxapp/templates/edxapp/mitxonline/common_values.yml#L252
> 
> If there's reason to think that the behavior of `ALLOW_PUBLIC_ACCOUNT_CREATION` has changed, I would be willing to try setting the flag. But we would need to be sure that account creation from the mitxonline application still works.

@pdpinch / @blarghmatey do we have any RC or CI LMS instance where we could test this functionality?

**Comment by blarghmatey** [comment]
Yes, we have an RC instance of edx that we can use for trying out this setting. Let me know when we would like to test the full functionality and I can coordinate getting the setting updated.

**Comment by umarmughal824** [comment]
> Yes, we have an RC instance of edx that we can use for trying out this setting. Let me know when we would like to test the full functionality and I can coordinate getting the setting updated.

Yeah we need to access it but we want to test it with `ALLOW_PUBLIC_ACCOUNT_CREATION =True`

**Comment by umarmughal824** [comment]
> Yes, we have an RC instance of edx that we can use for trying out this setting. Let me know when we would like to test the full functionality and I can coordinate getting the setting updated.

First of all, I have compared both xpro and online links both have the signup button and both let the public create an account over there.

I have tested out that `ALLOW_PUBLIC_ACCOUNT_CREATION = False` hides the Signup button in both from LMS and cms and also doesn't let any other way to create an account.

But we use that `ENABLE_REQUIRE_THIRD_PARTY_AUTH = True` that will make sure it only will load only supported IDP for account creation and we will add only supported or required IDP's. I guess that could be the solution for it.

**Comment by pdpinch** [comment]
@umarmughal824 if you think changing those settings will work, please open a PR to change the settings so we can test it.

**Comment by umarmughal824** [comment]
@blarghmatey could you please let me know where we could define that flag? I mean in any infrastructure repository or so.

**Comment by blarghmatey** [comment]
You can add that in one of the templates at https://github.com/mitodl/ol-infrastructure/tree/main/src/bilder/images/edxapp/templates/edxapp/mitxonline. If it's shared between CMS and LMS it goes in `common_values.yml`

**Comment by umarmughal824** [comment]
@blarghmatey could you please deploy it with new PR?

@pdpinch please test it after re-deploying. By that, whenever the user will go to the signup button, it will ask to create an account with MIT xOnline and no public registration form will be displayed. That fulfills our requirements if I am not wrong.

**Comment by pdpinch** [comment]
Well, the setting worked to hide the registration form, but it also blocked the mitxonline app from creating new accounts. 

Can we try overriding the template using the mitxonline-theme to hide the registration form?

**Comment by umarmughal824** [comment]
> Well, the setting worked to hide the registration form, but it also blocked the mitxonline app from creating new accounts.
> 
> Can we try overriding the template using the mitxonline-theme to hide the registration form?

We could do that I mean just removing/hiding the registration form codebase of our theme. Let me know what's your opinion on that. So that means in the future if we needed to show, we will have to add/show it back through a new PR. Is that what we need to do here?

**Comment by briangrossman** [comment]
@umarmughal824 
Peter found this PR (https://github.com/mitodl/mitxpro-theme/pull/9) that had a similar fix on xPRO. This could be helpful.
xPRO is a good reference for this issue.

**Comment by umarmughal824** [comment]
> @umarmughal824 Peter found this PR ([mitodl/mitxpro-theme#9](https://github.com/mitodl/mitxpro-theme/pull/9)) that had a similar fix on xPRO. This could be helpful. xPRO is a good reference for this issue.

@briangrossman that's already available in the theme. You could verify it here 
https://github.com/mitodl/mitxonline-theme/blob/main/lms/templates/student_account/login.underscore
