### ISSUE TITLE
Remove sysadmin link from the header

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline-theme#27]
As it's currently implemented, the sysdadmin link in the header causes a 500 error. 

See https://github.com/mitodl/mitxpro-theme/issues/40 from more details. 

I think this approach in the Residential MITx theme will fix it:

https://github.com/mitodl/mitx-theme/blob/0fa20947f8ffec2a34d77c77cb6e022ca566c2eb/lms/templates/navigation/bootstrap/navbar-authenticated.html#L12-L18

**Comment by arslanashraf7** [comment]
Closed via #28
